language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pip -U
  - pip install pytest==5.0.1
  - pip install -e .
  - pip install -e '.[tests]'

script:
  - ./test.sh
